---

- name: storage is managed, i.e. lvm, filesystems
  include_role:
    name: neo4j
    tasks_from: storage
  when: manage_storage

- name: neo4j is installed
  package:
    name: "{{ neo4j_package }}"
    state: installed

- name: neo4j is configured
  template:
    src: "{{ item }}"
    dest: /etc/neo4j/neo4j.conf
    backup: yes
  with_first_found:
    - "{{ playbook_dir }}/templates/{{ neo4j_cfg }}"
    - neo4j.conf.j2
  notify: restart neo4j

- name: neo4j is started
  service:
    name: neo4j
    state: started
    enabled: yes

